modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"
issueTrackerURL = "https://discord.gg/pHren9yxzW"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/cardiac"
authors = "${mod_authors}"
description = '''Pickable health orbs after mob death'''

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"